// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AniLand

import "strconv"

type Ftype int16

const (
	FtypeMove   Ftype = 0
	FtypeLogin  Ftype = 1
	FtypeAction Ftype = 2
)

var EnumNamesFtype = map[Ftype]string{
	FtypeMove:   "Move",
	FtypeLogin:  "Login",
	FtypeAction: "Action",
}

var EnumValuesFtype = map[string]Ftype{
	"Move":   FtypeMove,
	"Login":  FtypeLogin,
	"Action": FtypeAction,
}

func (v Ftype) String() string {
	if s, ok := EnumNamesFtype[v]; ok {
		return s
	}
	return "Ftype(" + strconv.FormatInt(int64(v), 10) + ")"
}
