// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package AniLand

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Move struct {
	_tab flatbuffers.Struct
}

func (rcv *Move) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Move) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Move) Pos(obj *Vec3) *Vec3 {
	if obj == nil {
		obj = new(Vec3)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}

func CreateMove(builder *flatbuffers.Builder, pos_x float32, pos_y float32, pos_z float32) flatbuffers.UOffsetT {
	builder.Prep(4, 12)
	builder.Prep(4, 12)
	builder.PrependFloat32(pos_z)
	builder.PrependFloat32(pos_y)
	builder.PrependFloat32(pos_x)
	return builder.Offset()
}
